# Generated by Django 5.1.6 on 2025-07-09 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doit_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='aprobado_cliente',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20, verbose_name='Estado de aprobación del cliente'),
        ),
    ]
