# Generated by Django 5.1.6 on 2025-07-10 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doit_app', '0002_customuser_aprobado_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='notificacion_calificar_descartada',
            field=models.BooleanField(default=False, verbose_name='Notificación de Calificar Descartada'),
        ),
    ]
