# Generated by Django 5.1.6 on 2025-06-16 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doit_app', '0003_alter_customuser_foto_perfil'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reserva',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AddField(
            model_name='customuser',
            name='hojaVida_file',
            field=models.FileField(blank=True, null=True, upload_to='hojas_de_vida/', verbose_name='Archivo de Hoja de Vida'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='evidenciaTrabajo',
            field=models.ImageField(blank=True, null=True, upload_to='evidencia_trabajo/', verbose_name='Evidencia de Trabajo (Imagen)'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='tipo_usuario',
            field=models.CharField(choices=[('usuario', 'Cliente'), ('experto', 'Experto')], default='usuario', max_length=20, verbose_name='Tipo de Usuario'),
        ),
    ]
