# Generated by Django 5.1.6 on 2025-07-10 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doit_app', '0003_reserva_notificacion_calificar_descartada'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='hoja_vida_file',
            field=models.FileField(blank=True, null=True, upload_to='hojas_vida/', verbose_name='Hoja de Vida (PDF)'),
        ),
    ]
