# Generated by Django 5.1.6 on 2025-07-10 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doit_app', '0004_customuser_hoja_vida_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='PQR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('peticion', 'Petición'), ('queja', 'Queja'), ('reclamo', 'Reclamo'), ('sugerencia', 'Sugerencia')], max_length=20, verbose_name='Tipo de PQR')),
                ('asunto', models.CharField(max_length=200, verbose_name='Asunto')),
                ('descripcion', models.TextField(verbose_name='Descripción detallada')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('respondido', models.BooleanField(default=False, verbose_name='¿Ha sido respondido?')),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de respuesta')),
                ('respuesta', models.TextField(blank=True, null=True, verbose_name='Respuesta del administrador')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que envía el PQR')),
            ],
            options={
                'verbose_name': 'PQR',
                'verbose_name_plural': 'PQRs',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
