# Generated by Django 5.1.6 on 2025-06-16 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doit_app', '0004_alter_reserva_options_customuser_hojavida_file_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reserva',
            options={'verbose_name': 'Reserva', 'verbose_name_plural': 'Reservas'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='tipo_usuario',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('experto', 'Experto')], default='usuario', max_length=20, verbose_name='Tipo de Usuario'),
        ),
    ]
